name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get tag Name
        run: |
          TAG_NAME=${GITHUB_REF_NAME}
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo "TAG_NAME=$TAG_NAME"

      - name: Create release artifact
        run: |
          zip -r release-${TAG_NAME}.zip . -x "*.yaml" "*.toml" "*.txt" "*.md" ".git*" ".docker*" "Dockerfile*"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: release-${{ env.TAG_NAME }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
